### ISSUE TITLE
xsd:date, xsd:time etc. do not work with OWL

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#62]
See https://www.w3.org/2017/10/24-hcls-minutes.html#item08

**Comment by dbooth-boston** [comment]
Eric has added this to the preprocessor: https://github.com/fhircat/fhir-rdf-playground/blob/7b79da834bb6b86e40a25586ff019df8ec0fdde9/fhirlib/FhirPreprocessors.js#L290

So it is now ready for me to document.

**Comment by dbooth-boston** [comment]
Done as polymorphic types are now addressed in R5

**Comment by tmprd** [comment]
Current usage of FHIR `xsd:date` is still not supported by OWL 2. We should document this somewhere like https://build.fhir.org/rdf.html#fhir-rdf-with-owl

Bonus points for adding a SPARQL script somewhere to convert to `xsd:dateTime` with invented values
